name: Generate Snake Game

on:
  schedule:
    # Jalankan setiap jam 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Build snake animation
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repositori
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Generate snake.svg menggunakan Platane/snk
      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: reno-25
          outputs: dist/github-contribution-grid-snake.svg

      # Step 3: Upload ke branch `output`
      - name: Push snake.svg to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
